## Spring config
spring:
  application:
    name: ms-browser-films
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/ms-browser-films}
    username: ${USR:postgres}
    password: ${PWD:admin$1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

## Instance config
server:
  port: 8088

## Eureka client config
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: false
    hostname: ms-browser-films